# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a92cc7510ddd396d25dd2fe6c8283c98cb86b4d4093df8e39f156dccca04b04eef6cd0693a5d78509fd5a563de4cde56b8d09c2a100962157662599a11f1501

test:
  secret_key_base: 10935da7212781d50ca52f69f4dcb358f33d6b5f362a7afcd9f71a6a8ae7d890cf073a7306f8e21f5e741011159b263dd598904d880eda989c0521aa7811835d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
